#!/usr/bin/env python3
from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_SEARCH_TUNING: dict[str, Any] = {
    "profile_family": "mixed",
    "variants_per_case": 4,
    "seed_fanout": 1,
    "batch_length": 12,
    "trace_length": 12,
    "gpu_nstates": 32,
    "campaign_gpu_nstates": 512,
    "campaign_sequential_rep_graph_mode": "auto",
    "gpu_reps": 3,
    "cpu_reps": 1,
    "states_per_case": 4,
    "keep_top_k": 16,
    "pilot_sweep_cases": 256,
    "pilot_campaign_candidate_count": 4096,
    "region_budget": {
        "reqfifo_storage_upper": 2,
        "rspfifo_storage_upper": 2,
        "response_payload": 2,
    },
    "driver_defaults": {},
}


SLICE_SEARCH_TUNING: dict[str, dict[str, Any]] = {
    "rom_ctrl_fsm": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 64,
        "trace_length": 20,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-rom-stream-low-to-kmac",
            "target-top-digest-capture-progress",
            "target-kmac-vs-rom-race-resolution",
            "target-checker-start-compare-done",
            "target-terminal-done-bus-select-or-alert",
        ],
        "region_budget": {
            "rom_stream_low_to_kmac": 1,
            "top_digest_capture_progress": 2,
            "kmac_vs_rom_race_resolution": 3,
            "checker_start_compare_done": 3,
            "terminal_done_bus_select_or_alert": 3,
        },
        "driver_defaults": {
            "batch_length": 64,
            "reset_cycles": 0,
            "drain_cycles": 24,
            "req_valid_pct": 100,
            "rsp_valid_pct": 100,
            "req_fill_target": 14,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 8,
            "rsp_fill_target": 3,
            "rsp_delay_max": 1,
        },
    },
    "lc_ctrl_fsm": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 128,
        "trace_length": 16,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-init-request-and-idle-progress",
            "target-clock-bypass-and-transition-progress",
            "target-token-hash-accept-vs-error",
            "target-otp-program-request-ack-progress",
            "target-flash-rma-and-terminal-error-path",
        ],
        "region_budget": {
            "init_request_and_idle_progress": 2,
            "clock_bypass_and_transition_progress": 2,
            "token_hash_accept_vs_error": 2,
            "otp_program_request_ack_progress": 2,
            "flash_rma_and_terminal_error_path": 2,
        },
        "driver_defaults": {
            "batch_length": 128,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 96,
            "rsp_valid_pct": 96,
            "req_fill_target": 10,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 8,
            "rsp_fill_target": 1,
            "rsp_delay_max": 1,
        },
    },
    "pwrmgr_fsm": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 32,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-powerup-request-ack-progress",
            "target-clock-enable-status-progress",
            "target-otp-lc-init-and-done",
            "target-low-power-entry-vs-abort-reset",
            "target-rom-check-and-fetch-enable-path",
        ],
        "region_budget": {
            "powerup_request_ack_progress": 2,
            "clock_enable_status_progress": 2,
            "otp_lc_init_and_done": 2,
            "low_power_entry_vs_abort_reset": 2,
            "rom_check_and_fetch_enable_path": 2,
        },
        "driver_defaults": {
            "batch_length": 32,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 96,
            "rsp_valid_pct": 96,
            "req_fill_target": 8,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 8,
            "rsp_fill_target": 1,
            "rsp_delay_max": 2,
        },
    },
    "alert_handler_ping_timer": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 24,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-edn-reseed-and-entropy",
            "target-alert-wait-issue-ack",
            "target-esc-wait-issue-ack",
            "target-id-skip-and-rotation",
            "target-fail-or-spurious-terminal",
        ],
        "region_budget": {
            "edn_reseed_and_entropy": 2,
            "alert_wait_issue_ack": 2,
            "esc_wait_issue_ack": 2,
            "id_skip_and_rotation": 2,
            "fail_or_spurious_terminal": 2,
        },
        "driver_defaults": {
            "batch_length": 24,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 92,
            "rsp_valid_pct": 94,
            "req_fill_target": 4,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 12,
            "rsp_fill_target": 2,
            "rsp_delay_max": 2,
        },
    },
    "alert_handler_esc_timer": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 24,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-timeout-countdown-progress",
            "target-phase0-entry-and-crashdump",
            "target-phase1-phase2-progress",
            "target-phase3-terminal-escalation",
            "target-fsm-error-or-counter-fault",
        ],
        "region_budget": {
            "timeout_countdown_progress": 2,
            "phase0_entry_and_crashdump": 2,
            "phase1_phase2_progress": 2,
            "phase3_terminal_escalation": 2,
            "fsm_error_or_counter_fault": 2,
        },
        "driver_defaults": {
            "batch_length": 24,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 92,
            "rsp_valid_pct": 94,
            "req_fill_target": 4,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 12,
            "rsp_fill_target": 2,
            "rsp_delay_max": 2,
        },
    },
    "entropy_src_main_sm": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 80,
        "trace_length": 16,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-boot-bypass-progress",
            "target-startup-health-test-progress",
            "target-continuous-sha3-pipeline",
            "target-fw-override-insert-and-digest",
            "target-alert-or-error-terminal",
        ],
        "region_budget": {
            "boot_bypass_progress": 2,
            "startup_health_test_progress": 2,
            "continuous_sha3_pipeline": 2,
            "fw_override_insert_and_digest": 2,
            "alert_or_error_terminal": 2,
        },
        "driver_defaults": {
            "batch_length": 80,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 92,
            "rsp_valid_pct": 96,
            "req_fill_target": 6,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 12,
            "rsp_fill_target": 2,
            "rsp_delay_max": 4,
        },
    },
    "aes_cipher_control": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 24,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-input-output-handshake-progress",
            "target-cipher-vs-keyexpand-dispatch",
            "target-subbytes-wait-vs-ack",
            "target-prng-reseed-and-clear-control",
            "target-alert-or-multirail-error",
        ],
        "region_budget": {
            "input_output_handshake_progress": 2,
            "cipher_vs_keyexpand_dispatch": 2,
            "subbytes_wait_vs_ack": 2,
            "prng_reseed_and_clear_control": 2,
            "alert_or_multirail_error": 2,
        },
        "driver_defaults": {
            "batch_length": 24,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 92,
            "rsp_valid_pct": 92,
            "host_d_ready_pct": 64,
            "device_a_ready_pct": 64,
            "req_fill_target": 4,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 6,
            "rsp_fill_target": 2,
            "rsp_delay_max": 4,
        },
    },
    "csrng_main_sm": {
        "profile_family": "mixed",
        "variants_per_case": 5,
        "seed_fanout": 1,
        "batch_length": 24,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-command-parse-progress",
            "target-entropy-wait-vs-direct-issue",
            "target-instantiate-reseed-generate-update-split",
            "target-command-complete-return",
            "target-terminal-error-hold",
        ],
        "region_budget": {
            "command_parse_progress": 2,
            "entropy_wait_vs_direct_issue": 2,
            "instantiate_reseed_generate_update_split": 2,
            "command_complete_return": 2,
            "terminal_error_hold": 2,
        },
        "driver_defaults": {
            "batch_length": 24,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 92,
            "rsp_valid_pct": 96,
            "req_fill_target": 8,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 4,
            "rsp_fill_target": 1,
            "rsp_delay_max": 2,
        },
    },
    "edn_main_sm": {
        "profile_family": "mixed",
        "variants_per_case": 6,
        "seed_fanout": 1,
        "batch_length": 24,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "target-boot-sequence-progress",
            "target-auto-request-progress",
            "target-software-port-accept",
            "target-reseed-vs-generate-dispatch",
            "target-request-accept-and-progress",
            "target-reject-or-error-terminal",
        ],
        "region_budget": {
            "boot_sequence_progress": 2,
            "auto_request_progress": 2,
            "software_port_accept": 2,
            "reseed_vs_generate_dispatch": 2,
            "request_accept_and_progress": 2,
            "reject_or_error_terminal": 2,
        },
        "driver_defaults": {
            "batch_length": 24,
            "reset_cycles": 4,
            "drain_cycles": 16,
            "req_valid_pct": 88,
            "rsp_valid_pct": 96,
            "req_fill_target": 6,
            "req_family": 0,
            "req_address_mode": 0,
            "req_data_mode": 0,
            "rsp_error_pct": 6,
            "rsp_fill_target": 2,
            "rsp_delay_max": 4,
            "rsp_family": 0,
        },
    },
    "tlul_fifo_sync": {
        "profile_family": "mixed",
        "variants_per_case": 4,
        "seed_fanout": 1,
        "batch_length": 12,
        "trace_length": 12,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "always",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "region_budget": {
            "reqfifo_storage_upper": 4,
            "rspfifo_storage_upper": 3,
            "response_payload": 1,
        },
    },
    "tlul_request_loopback": {
        "profile_family": "mixed",
        "variants_per_case": 6,
        "seed_fanout": 1,
        "batch_length": 48,
        "trace_length": 16,
        "gpu_nstates": 32,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "auto",
        "states_per_case": 4,
        "keep_top_k": 16,
        "pilot_sweep_cases": 256,
        "pilot_campaign_candidate_count": 4096,
        "trace_variants": [
            "base",
            "target-control-and-squash",
            "target-forward-request",
            "target-loopback-response",
            "target-target-response-passthrough",
            "target-progress-and-backpressure",
        ],
        "region_budget": {
            "control_and_squash": 2,
            "forward_request_path": 2,
            "loopback_response_path": 2,
            "target_response_passthrough": 2,
            "progress_and_backpressure": 2,
        },
        "driver_defaults": {
            "batch_length": 48,
            "drain_cycles": 64,
            "req_valid_pct": 96,
            "rsp_valid_pct": 96,
            "host_d_ready_pct": 92,
            "device_a_ready_pct": 92,
            "put_full_pct": 20,
            "put_partial_pct": 20,
            "req_fill_target": 8,
            "req_burst_len_max": 4,
            "req_family": 1,
            "req_address_mode": 1,
            "req_data_mode": 2,
            "req_data_hi_xor": 0x00FF0000,
            "access_ack_data_pct": 100,
            "rsp_error_pct": 12,
            "rsp_fill_target": 1,
            "rsp_delay_max": 1,
            "rsp_family": 1,
            "rsp_delay_mode": 0,
            "rsp_data_mode": 1,
            "rsp_data_hi_xor": 0xFFFF0000,
            "address_mask": 0x00000FFC,
            "source_mask": 0x0000003F,
        },
    },
    "tlul_socket_1n": {
        "profile_family": "dead-region",
        "variants_per_case": 10,
        "seed_fanout": 1,
        "batch_length": 48,
        "trace_length": 24,
        "gpu_nstates": 64,
        "campaign_gpu_nstates": 256,
        "campaign_sequential_rep_graph_mode": "always",
        "states_per_case": 4,
        "keep_top_k": 24,
        "pilot_sweep_cases": 384,
        "pilot_campaign_candidate_count": 6144,
        "region_budget": {
            "reqfifo_storage_upper": 6,
            "rspfifo_storage_upper": 6,
            "response_payload": 8,
        },
        "driver_defaults": {
            "batch_length": 48,
            "drain_cycles": 72,
            "req_valid_pct": 92,
            "rsp_valid_pct": 96,
            "host_d_ready_pct": 92,
            "device_a_ready_pct": 88,
            "req_fill_target": 2,
            "req_burst_len_max": 10,
            "req_family": 2,
            "req_address_mode": 2,
            "req_data_mode": 4,
            "req_data_hi_xor": 0xFF00FF00,
            "access_ack_data_pct": 96,
            "rsp_fill_target": 2,
            "rsp_delay_max": 1,
            "rsp_family": 3,
            "rsp_delay_mode": 0,
            "rsp_data_mode": 4,
            "rsp_data_hi_xor": 0x00FF0000,
            "put_full_pct": 78,
            "put_partial_pct": 8,
            "address_mask": 0x00000FFC,
            "source_mask": 0x0000003F,
        },
    },
    "tlul_socket_m1": {
        "profile_family": "dead-region",
        "variants_per_case": 10,
        "seed_fanout": 1,
        "batch_length": 56,
        "trace_length": 24,
        "gpu_nstates": 64,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "always",
        "states_per_case": 4,
        "keep_top_k": 24,
        "pilot_sweep_cases": 384,
        "pilot_campaign_candidate_count": 6144,
        "trace_variants": [
            "target-routing-control",
            "target-device-request-merge",
            "target-response-select-path",
            "target-host-response-path",
            "target-error-or-drop-path",
        ],
        "region_budget": {
            "routing_control": 3,
            "device_request_merge": 3,
            "response_select_path": 3,
            "host_response_path": 3,
            "error_or_drop_path": 2,
        },
        "driver_defaults": {
            "batch_length": 56,
            "drain_cycles": 80,
            "req_valid_pct": 94,
            "rsp_valid_pct": 96,
            "host_d_ready_pct": 72,
            "device_a_ready_pct": 72,
            "req_fill_target": 4,
            "req_burst_len_max": 12,
            "req_family": 2,
            "req_address_mode": 1,
            "req_data_mode": 2,
            "req_data_hi_xor": 0xFFFF0000,
            "access_ack_data_pct": 98,
            "rsp_fill_target": 3,
            "rsp_delay_max": 2,
            "rsp_family": 2,
            "rsp_delay_mode": 1,
            "rsp_data_mode": 4,
            "rsp_data_hi_xor": 0xFFF00000,
            "put_full_pct": 88,
            "put_partial_pct": 4,
            "address_mask": 0x00000FFC,
            "source_mask": 0x0000003F,
        },
    },
    "xbar_main": {
        "profile_family": "dead-region",
        "variants_per_case": 10,
        "seed_fanout": 1,
        "batch_length": 64,
        "trace_length": 28,
        "gpu_nstates": 64,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "never",
        "states_per_case": 4,
        "keep_top_k": 24,
        "pilot_sweep_cases": 384,
        "pilot_campaign_candidate_count": 6144,
        "region_budget": {
            "reqfifo_storage_upper": 3,
            "rspfifo_storage_upper": 3,
            "response_payload": 6,
        },
        "driver_defaults": {
            "batch_length": 64,
            "drain_cycles": 96,
            "req_valid_pct": 94,
            "rsp_valid_pct": 96,
            "host_d_ready_pct": 92,
            "device_a_ready_pct": 92,
            "req_fill_target": 2,
            "req_burst_len_max": 12,
            "req_family": 3,
            "req_address_mode": 3,
            "req_data_mode": 4,
            "req_data_hi_xor": 0xFFFF0000,
            "access_ack_data_pct": 100,
            "rsp_fill_target": 2,
            "rsp_delay_max": 0,
            "rsp_family": 3,
            "rsp_delay_mode": 0,
            "rsp_data_mode": 4,
            "rsp_data_hi_xor": 0xFFF00000,
            "put_full_pct": 88,
            "put_partial_pct": 4,
            "address_mask": 0x00000FFC,
            "source_mask": 0x0000003F,
        },
    },
    "xbar_peri": {
        "profile_family": "dead-region",
        "variants_per_case": 10,
        "seed_fanout": 1,
        "batch_length": 56,
        "trace_length": 24,
        "gpu_nstates": 64,
        "campaign_gpu_nstates": 512,
        "campaign_sequential_rep_graph_mode": "never",
        "states_per_case": 4,
        "keep_top_k": 24,
        "pilot_sweep_cases": 384,
        "pilot_campaign_candidate_count": 6144,
        "region_budget": {
            "reqfifo_storage_upper": 4,
            "rspfifo_storage_upper": 4,
            "response_payload": 6,
        },
        "driver_defaults": {
            "batch_length": 56,
            "drain_cycles": 88,
            "req_valid_pct": 94,
            "rsp_valid_pct": 96,
            "host_d_ready_pct": 92,
            "device_a_ready_pct": 92,
            "req_fill_target": 2,
            "req_burst_len_max": 10,
            "req_family": 3,
            "req_address_mode": 2,
            "req_data_mode": 4,
            "req_data_hi_xor": 0xFF00FF00,
            "access_ack_data_pct": 98,
            "rsp_fill_target": 2,
            "rsp_delay_max": 0,
            "rsp_family": 3,
            "rsp_delay_mode": 0,
            "rsp_data_mode": 4,
            "rsp_data_hi_xor": 0x00FF0000,
            "put_full_pct": 84,
            "put_partial_pct": 6,
            "address_mask": 0x00000FFC,
            "source_mask": 0x0000003F,
        },
    },
}


def resolve_slice_search_tuning(
    slice_name: str,
    template_args: dict[str, Any] | None = None,
) -> dict[str, Any]:
    tuning = deepcopy(DEFAULT_SEARCH_TUNING)
    tuning.update(deepcopy(SLICE_SEARCH_TUNING.get(str(slice_name), {})))
    if template_args:
        for key in (
            "profile_family",
            "variants_per_case",
            "trace_variants",
            "seed_fanout",
            "batch_length",
            "trace_length",
            "gpu_nstates",
            "campaign_gpu_nstates",
            "campaign_sequential_rep_graph_mode",
            "gpu_reps",
            "cpu_reps",
            "states_per_case",
            "keep_top_k",
            "pilot_sweep_cases",
            "pilot_campaign_candidate_count",
            "region_budget",
        ):
            if template_args.get(key) is not None:
                tuning[key] = template_args[key]
        template_driver_defaults = dict(template_args.get("driver_defaults") or {})
        if template_driver_defaults:
            merged_driver_defaults = dict(tuning.get("driver_defaults") or {})
            merged_driver_defaults.update(template_driver_defaults)
            tuning["driver_defaults"] = merged_driver_defaults
    return tuning
