#!/usr/bin/env python3
"""
gen_vl_gpu_kernel.py
Verilator --cc + clang++ -emit-llvm の merged.ll から
NVPTX GPU カーネルを生成する。

戦略:
  1. _eval から到達する define 済み関数だけ抽出
  2. 外部関数 (VL_FATAL_MT 等) を no-op stub に置き換え
  3. NVPTX ターゲット設定
  4. AoS-strided カーネルを追加
       thread i → _eval(base + i * storage_size)

Usage:
  python3 gen_vl_gpu_kernel.py <merged.ll> <storage_size> [out_gpu.ll]
"""

import re
import sys
from pathlib import Path

from llvm_ir_parse import extract_functions, reachable_from, external_calls
from llvm_stub_gen import make_no_op_stub
from vl_runtime_filter import is_runtime, detect_vlsyms_offset

NVPTX_DATALAYOUT = 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'
NVPTX_TRIPLE     = 'nvptx64-nvidia-cuda'


def generate_gpu_ll(merged_ll_path: Path, storage_size: int) -> str:
    text = merged_ll_path.read_text(encoding='utf-8')

    all_funcs = extract_functions(text)

    # _eval 関数名を特定 (___024root___eval で終わる)
    eval_fn = None
    for name in all_funcs:
        if re.search(r'___024root___evalP', name) and '___eval_' not in name:
            eval_fn = name
            break
    if eval_fn is None:
        for name in all_funcs:
            if '_eval' in name and re.search(
                r'define\s+void\s+@' + re.escape(name) + r'\s*\(ptr', text
            ):
                eval_fn = name
                break
    if eval_fn is None:
        raise RuntimeError('_eval 関数が見つかりません')
    print(f'eval 関数: @{eval_fn}')

    needed_raw = reachable_from(eval_fn, all_funcs)
    print(f'到達可能な define 関数 (raw): {len(needed_raw)} 個')

    needed = {n for n in needed_raw if not is_runtime(n, all_funcs.get(n, ''))}
    forced_stubs = needed_raw - needed
    print(f'到達可能な define 関数 (GPU対象): {len(needed)} 個')
    if forced_stubs:
        print(f'ランタイム関数を stub 化: {len(forced_stubs)} 個')

    ext = external_calls(needed, all_funcs) | forced_stubs
    print(f'stub 必要な外部関数: {len(ext)} 個')

    vlsyms_offset = detect_vlsyms_offset(text)
    if vlsyms_offset is not None:
        print(f'vlSymsp オフセット: {vlsyms_offset} bytes (fake_syms_buf で null-safe 化)')
    else:
        print('vlSymsp オフセット: 未検出 (vlSyms 初期化スキップ)')

    lines = []
    lines.append('; NVPTX GPU kernel — auto-generated by gen_vl_gpu_kernel.py')
    lines.append(f'; Storage size: {storage_size} bytes / state')
    lines.append(f'; eval function: @{eval_fn}')
    if vlsyms_offset is not None:
        lines.append(f'; vlSymsp offset: {vlsyms_offset} (initialized to @fake_syms_buf)')
    lines.append('')
    lines.append(f'target datalayout = "{NVPTX_DATALAYOUT}"')
    lines.append(f'target triple = "{NVPTX_TRIPLE}"')
    lines.append('')

    # 型定義
    for line in text.splitlines():
        if re.match(r'^%.*=\s*type\s', line):
            lines.append(line)
    lines.append('')

    # fake_syms_buf: ico_sequent / nba_comb の vlSyms デリファレンスを null-safe にする
    # サイズ 4096: Syms 内の embedded root (offset ~192) + root fields (~2048) を余裕でカバー
    if vlsyms_offset is not None:
        lines.append('@fake_syms_buf = internal global [4096 x i8] zeroinitializer, align 64')
        lines.append('')

    # グローバル変数定義マップ (@.str.* 以外)
    global_defs: dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r'^(@[\w.]+)\s*=', line)
        if m and not re.match(r'^@\.str', line):
            global_defs[m.group(1)] = line

    # 文字列定数 (@.str.*)
    for line in text.splitlines():
        if re.match(r'^@\.str', line):
            lines.append(line)

    # switch table 等、関数本体から参照される非関数グローバル
    needed_globals: set[str] = set()
    for fn_name in needed:
        for ref in re.findall(r'@([\w.]+)', all_funcs[fn_name]):
            gname = f'@{ref}'
            if gname in global_defs:
                needed_globals.add(gname)
    if needed_globals:
        lines.append('; referenced globals (switch tables, const data, ...)')
        for gname in sorted(needed_globals):
            lines.append(global_defs[gname])
    lines.append('')

    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    # lowerinvoke + vl-strip-x86-attrs が personality を除去するまでの参照先として必要
    lines.append('declare i32 @__gxx_personality_v0(...)')
    lines.append('')

    # no-op stub
    for ext_fn in sorted(ext):
        lines.append(f'; stub: {ext_fn}')
        lines.append(make_no_op_stub(ext_fn, text))

    # 関数本体 (変換は opt --load-pass-plugin=VlGpuPasses.so で実施)
    for fn_name in sorted(needed):
        lines.append(all_funcs[fn_name])
        lines.append('')

    # AoS-strided GPU カーネル
    lines.append('; === GPU kernel: batch_gpu ===')
    lines.append(f'define void @vl_eval_batch_gpu(ptr %storage_base, i32 %nstates) {{')
    lines.append('entry:')
    lines.append('  %tid  = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()')
    lines.append('  %bid  = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()')
    lines.append('  %bdim = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()')
    lines.append('  %gid_mul = mul i32 %bid, %bdim')
    lines.append('  %gid32   = add i32 %gid_mul, %tid')
    lines.append('  %in_range = icmp ult i32 %gid32, %nstates')
    lines.append('  br i1 %in_range, label %body, label %exit')
    lines.append('')
    lines.append('body:')
    lines.append('  %gid    = zext i32 %gid32 to i64')
    lines.append(f'  %stride = add i64 {storage_size}, 0')
    lines.append('  %offset = mul i64 %gid, %stride')
    lines.append('  %state_ptr = getelementptr inbounds i8, ptr %storage_base, i64 %offset')
    if vlsyms_offset is not None:
        lines.append(f'  %vlsyms_gep = getelementptr inbounds i8, ptr %state_ptr, i64 {vlsyms_offset}')
        lines.append('  store ptr @fake_syms_buf, ptr %vlsyms_gep, align 8')
    lines.append(f'  call void @{eval_fn}(ptr %state_ptr)')
    lines.append('  br label %exit')
    lines.append('')
    lines.append('exit:')
    lines.append('  ret void')
    lines.append('}')
    lines.append('')

    # TBAA / prof メタデータ
    meta_lines = []
    max_id = -1
    for line in text.splitlines():
        if re.match(r'^!\d+\s*=', line):
            mid = int(re.match(r'^!(\d+)', line).group(1))
            max_id = max(max_id, mid)
            meta_lines.append(line)
    lines.extend(meta_lines)
    lines.append('')

    kernel_id = max_id + 1
    lines.append(f'!{kernel_id} = !{{ptr @vl_eval_batch_gpu, !"kernel", i32 1}}')
    lines.append(f'!nvvm.annotations = !{{!{kernel_id}}}')

    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <merged.ll> <storage_size> [out_gpu.ll]')
        sys.exit(1)

    merged_ll  = Path(sys.argv[1])
    storage_sz = int(sys.argv[2])
    out_path   = Path(sys.argv[3]) if len(sys.argv) > 3 \
                 else merged_ll.parent / 'vl_batch_gpu.ll'

    gpu_ll = generate_gpu_ll(merged_ll, storage_sz)
    out_path.write_text(gpu_ll, encoding='utf-8')
    print(f'Written: {out_path}')


if __name__ == '__main__':
    main()
